- miniupnpd/netfilter/iptcrdr.c
In get_portmappings_in_range(), array[] is not updated when realloc() is not called, 
hence get_portmappings_in_range() is always null.  This fix changes to fill array[].
> Fix get_portmappings_in_range() in non-expand case.

- miniupnpc/CMakeLists.txt
Each `COMPILE_DEFINITIONS` passed to `set_source_file_properties ()` overrides previous value, so only `MINIUPNP_EXPORTS` is left in the end. Pass single `COMPILE_DEFINITIONS` and combine needed definitions into `;`-separated list manually.
> Fix MINIUPNP_STATICLIB being lost in CMake configuration

- miniupnpc/miniupnpcmodule.c
- miniupnpc/pymoduletest.py
Example: `pymoduletest.py -m br0` 
Full help:
```
$ pymoduletest.py -h
usage: pymoduletest.py [-h] [-m MULTICASTIF] [-p MINISSDPDSOCKET]
[-d DISCOVERDELAY]
optional arguments:
-h, --help            show this help message and exit
-m MULTICASTIF, --multicastif MULTICASTIF
-p MINISSDPDSOCKET, --minissdpdsocket MINISSDPDSOCKET
-d DISCOVERDELAY, --discoverdelay DISCOVERDELAY
```
> Specify interface and other params in python module

- minissdpd/config.h
- minissdpd/minissdpd.c
- minissdpd/testminissdpd.c
On networks with many upnp devices, type 3 search truncates at 4K (Line 729: minissdpd/minissdpd.c).  This translates to about 32 devices.  Update config.h RESPONSE_BUFFER_SIZE as needed before make.  By default,  the buffer size remains the same so that memory profile is not altered.  In my use case, 32K bufffer size can yield 190 devices in IPv4.  We use 50K as our setting which should support all devices on a /24 network.
> Add #define for unix socket response buffer size

- miniupnpd/genconfig.sh
- miniupnpd/linux/getifstats.c
- miniupnpd/upnphttp.c
The changes include removal of an unused Tomato specific include in genconfig.sh, reduction of severity of one message to reduce verbosity, and addition of client info to a log message.
If merged, these changes will allow Tomato developers to more easilly incorporate updates to miniupnpd into Tomato.
A separate PR will be create for a Tomato specific item in miniupnpd.c, as that one will be slightly larger (although still impact-less to generic miniupnpd).
> Minor Changes Proposed to Allow Easier Merge of Upstream to Tomato

- miniupnpd/genconfig.sh
As discussed in this thread:
http://www.linksysinfo.org/index.php?threads/tomato-shibbys-releases.33858/page-53#post-262636
It appears that the Tomato OS_VERSION has gotten long enough, that it's causing SSDP_PACKET_MAX_LEN being larger than 512 by a few characters.
This change reduces unnecessary "verbiage" at the end of the Tomato OS_VERSION string.
In short, what was previously (as example):
Tomato 1.28.0000 MIPSR2-130 K26AC USB AIO-64K
will become
Tomato MIPSR2-130 K26AC
> Make Tomato's OS_VERSION shorter to stop SendSSDPNotify log messages

- miniupnpc/setup.py
This move to setuptools allows to build (relatively) new binary wheel distribution and keep current source distribution (https://pypi.python.org/pypi/miniupnpc/1.9) as well.
The miniupnpc is done in native code. In many cases you just want to get compiled working binaries compatible with the platform without recompiling them. This is critical for ARM processors, since compile time there is much longer.
The choice of setuptools and bdist_wheel is inline with latest python packaging recommendations: https://packaging.python.org/en/latest/current.html.
> Moving to setuptools to enable wheel

- miniupnpc/listdevices.c
- miniupnpc/minissdpc.c
- miniupnpc/miniupnpc.c
- miniupnpc/miniupnpc.h
USN is mandatory header so nothing should break.
Yes, this breaks ABI of miniupnpc, but I think it's worth it (descURL is not guaranteed to be constant, and I need unique service identifiers)
Note that I've changed listdevices to print USN instead of ST - may be not what you want in this tool.
> Read USN from SSDP messages.

- miniupnpc/minissdpc.c
- miniupnpc/minissdpc.h
- miniupnpc/miniupnpc.c
This change is split into 3 patches to simplify review. If you don't like my naming choices I'll readily change them.
In my application I implement DLNA, and I use only SSDP part of MiniUPnP with different implementations of HTTP and SOAP. (There are a lot of library options for HTTP and SOAP, but much less for SSDP).
I'd like to have minssdpc as a generic SSDP client library which can either use MiniSSDPd or fallback to in-process SSDP request. If you have no objections, I'll move request and receive parts of upnpDiscoverDevices into minssdpc too.
> Allow using persistent socket connection in minissdpc

- minissdpd/getroute.c
Same as a93028913cfe024f3d04e1c216116b1a66af4134 for miniupnpd
Fixes
```
getroute.c: In function 'get_src_for_route_to':
getroute.c:175:80: warning: format '%lu' expects argument of type 'long unsigned int', but argument  has type 'unsigned int' [-Wformat=]
(unsigned)*src_len, RTA_PAYLOAD(rta));
^
```
> minissdpd: Fix compiler warning

- miniupnpd/minissdp.c
- miniupnpd/miniupnpd.c
- miniupnpd/upnpglobalvars.c
- miniupnpd/upnpglobalvars.h
This is needed when you have two interfaces with the same IP address
(for example using tinc).
This is not supported when you have MULTIPLE_EXTERNAL_IP
> miniupnpd: Bind to device

- miniupnpc/man3/miniupnpc.3
- miniupnpc/miniupnpc.c
- miniupnpc/miniupnpc.h
- miniupnpc/miniupnpcmodule.c
- miniupnpc/pymoduletest.py
- miniupnpc/upnpc.c
See https://github.com/miniupnp/miniupnp/issues/119
- Replace the `sameport` parameter to the upnpDiscover* functions with `localport`
- Added constants UPNP_LOCAL_PORT_ANY(0) & UPNP_LOCAL_PORT_SAME(1).  The
value "1" was chosen for presumed backwards compatibility with the
previous "sameport" parameter (assuming usesr would have set to 1 if
they wanted same port)
- Can be specified with `-z` to the test programs `upnpc` & `pymoduletest.py`
> Allow user to explicitly specify local (source) port

- miniupnpc/minisoap.c
- miniupnpc/minissdpc.c
- miniupnpc/miniupnpc.c
- miniupnpc/miniwget.c
I found these bugs during a security audit of miniupnpc in the context of TALOS-2015-0035 in Bitcoin Core, and tried to fix them.
Neither of these are remote vulnerabilities, as they are triggered by input from the application not from the network. However they lead to exposure of memory contents or stack overflows when used as part of a multi-pronged exploit.
- Check return value of snprintf: snprintf on Linux returns the number of characters that would have been written if there was enough space in the buffer. Return an error condition if space was not sufficient.
- Account exactly for bytes when building buffer in simpleUPnPcommand2. The margin of 100 is not guaranteed to always be enough. When long parameters are passed in, it was possible to overflow the buffer.
> String handling fixes

- miniupnpd/upnpdescgen.c
Per the [IGDv2 spec](http://upnp.org/specs/gw/UPnP-gw-InternetGatewayDevice-v2-Device.pdf) (see Table 1 in Section 2.2 or the XML in Section 3), the serviceId for the Layer3Forwarding service should be "L3Forwarding1".
> fix Layer3Forwarding serviceId to be consistent with IGDv2 spec

- miniupnpc/miniupnpc.c
The LAN address is sometimes overwritten by a non-IGD entry. This results in a otherwise valid IGD not getting detected correctly, based on the order of the advertised devices.
> Bug fix in returned IGD LAN address

- miniupnpd/upnpevents.c
- miniupnpd/upnpevents.h
- miniupnpd/upnphttp.c
Per the spec, renew responses should have the same format as subscription responses, and as such they should include the SID: field. Found this using the "Intel Device Validator for UPnP Technologies" tool.
> return SID in renew response

- miniupnpd/minissdp.c
- miniupnpd/upnpsoap.c
The device and service notifications generated by miniupnpd use the IGDv1 versions of the various device and service descriptors even when compiling with IGDv2 enabled. They should always match the values in rootDesc.xml. This issue was flagged by the "Intel Device Validator for UPnP Technologies" tool.
> advertise correct service and device versions when IGDv2 is enabled

- miniupnpd/upnpdescgen.c
- miniupnpd/upnpsoap.c
The definitions for the three actions for the DeviceProtection service are missing the parameters defined in [the spec](http://upnp.org/specs/gw/UPnP-gw-DeviceProtection-v1-Service.pdf). Also, the tags in the responses are incorrect (bogus "New" prefix).
> fix action arguments for DeviceProtection service

- miniupnpd/upnpsoap.c
The argument parsing code was still using the "New" prefixes for the arguments.
> fix parsing of input arguments in SendSetupMessage()

- miniupnpd/upnpdescgen.c
The SetupReady value in the event notification for the DeviceProtection service is empty, not a valid boolean.
> actually return a value in SetupReady notifications

- miniupnpd/ipf/ipfrdr.c
- miniupnpd/ipfw/ipfwrdr.c
- miniupnpd/miniupnpd.c
- miniupnpd/netfilter/iptpinhole.c
- miniupnpd/pcplearndscp.c
- miniupnpd/portinuse.c
Found by cppcheck. There are some warnings leftover, but it seems to be small that I don't bother touch it.
> Fix memory leak when realloc fails

- miniupnpd/genconfig.sh
- miniupnpd/portinuse.c
- fix a few build issues
- when built with ENABLE_IPV6, miniupnpd didn't respond to requests made to its IPv4 addresses.
> A few fixes for miniupnpd on DragonFly BSD

- miniupnpc/CMakeLists.txt
I imported miniupnp as a git submodule in my cmake project and I was getting build errors. CMAKE_SOURCE_DIR always returns the path to the top-level cmake project, which is my project in this case (adding miniupnpc with add_subdirectory). CMAKE_CURRENT_SOURCE_DIR points to the intended directory instead. The same is true for CMAKE_BINARY_DIR/CMAKE_CURRENT_BINARY_DIR.
> Fix cmake file so project can be used as a subproject

- miniupnpd/genconfig.sh
Whilst working on the Reproducible Builds effort [0], we noticed that
miniupnpd could not be built reproducibly due to embedded timestamps.
[0] https://reproducible-builds.org/
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>
> Please make the build reproducible

- miniupnpc/CMakeLists.txt
CMAKE_COMPILER_IS_GNUC should be CMAKE_COMPILER_IS_GNUCC.
There is no variable named CMAKE_COMPILER_IS_GNUC, so the statements under if would never run.
> Fix issue in CMakeLists.txt.

- miniupnpd/portinuse.c
To allow for "drop-in" upgrades of Miniupnp within Tomato firmware, submitting this change back upstream.
Original source:  https://bitbucket.org/kille72/tomato-arm-kille72/commits/b9d9e4b0ed761c6cdddd1227676b08bce2934481?at=shibby-arm
Have used ifdef for clarity of why the "new" entry is there (i.e. Tomato)
> Adding Tomato ifdef for netfilter chain to check

- miniupnpc/miniupnpcmodule.c
- miniupnpc/setup.py
This allows to build the module directly via `pip`.
> miniupnpc:py: build libminiupnpc.a

- miniupnpc-libevent/miniupnpc-libevent.c
There is a small error in miniupnpc-libevent.c: wrong matched parentheses in function "set multicast TTL" line 744
> fix error of wrong matched parentheses in miniupnpc-libevent.c

- miniupnpd/upnpevents.c
Adds the IP and port of requesting host when a send error is logged to syslog so that it is possible to identify the application causing the problem.  Copied the syntax used for Connect() errors in same file.
> Add source IP and port to syslog for upnp_event_send() error.

- miniupnpc/external-ip.sh
change sed pattern to only match when GetExternalIPAaddress succeeds and output nothing if it fails
```
$ upnpc -s | grep ExternalIPAddress | sed 's/[^0-9\.]//g'
.3
$ upnpc -s | grep ExternalIPAddress 
GetExternalIPAddress failed. (errorcode=-3)
$ upnpc -s | sed -n -e 's/^ExternalIPAddress = \([0-9.]*\)$/\1/p'
$
```
> Update external-ip.sh, only output on success

- miniupnpd/miniupnpd.c
- miniupnpd/miniupnpd.conf
- miniupnpd/options.c
- miniupnpd/options.h
- miniupnpd/testupnpdescgen.c
- miniupnpd/upnpdescgen.c
Towards miniupnp/miniupnp#277
Hopefully this allows people running distros that blindly enable v2 to override it at run time.
tested with windows 10 and windows 7 upnp clients
> Allow runtime override of igd to v1 for people running binaries with v2 enabled

- miniupnpd/Makefile
- miniupnpd/Makefile.linux
- miniupnpd/Makefile.linux_nft
- miniupnpd/Makefile.macosx
- miniupnpd/Makefile.sunos
- miniupnpd/getifaddr.c
- miniupnpd/getifaddr.h
- miniupnpd/miniupnpd.c
- miniupnpd/miniupnpd.conf
- miniupnpd/natpmp.c
- miniupnpd/netfilter/iptcrdr.c
- miniupnpd/netfilter/iptcrdr.h
- miniupnpd/options.c
- miniupnpd/options.h
- miniupnpd/pf/obsdrdr.c
- miniupnpd/pf/obsdrdr.h
- miniupnpd/testupnpdescgen.c
- miniupnpd/upnpdescgen.c
- miniupnpd/upnpglobalvars.c
- miniupnpd/upnpglobalvars.h
- miniupnpd/upnpredirect.c
- miniupnpd/upnpsoap.c
- miniupnpd/upnpstun.c
- miniupnpd/upnpstun.h
Normally port forwarding works only in case miniupnpd have public IP address and it is not running on network hidden behind NAT.
There is one exception: when miniupnpd host has private IP address with unrestricted NAT 1:1 -- i.e. it private IP address has 1:1 mapping with some public IP address and all incoming packets to public IP address are NAT-ed to private IP address without any filtering or dropping. In some countries this is common behavior of ISPs how to provide public external IP address.
This pull request implements STUN client protocol for learning external IP address and NAT type via external STUN server. This feature is disabled by default and user can enable it via config options `ext_perform_stun`, `ext_stun_host` and `ext_stun_port`.
When sending STUN binding requests we …
> miniupnpd: Learn public IP address and detect NAT via STUN protocol

- miniupnpd/miniupnpd.c
Also update help for -o STUN: option, it can take stun hostname too.
> miniupnpd: Allow to specify also port number in -o STUN: option

- miniupnpc/README
Configuring iptables firewall for UPnP clients to not be too relax is not easy. This is because netfilter's conntrack module cannot track unicast UDP responses for UDP packets sent to multicast address. Most users either turn firewall off or accept any incoming UDP packets to have UPnP clients working.
But with introduction of ipset into Linux kernel >= 2.6.39 it is possible to have iptables set to fully restrictive mode (-P DROP) and allow UPnP clients working.
I think that it can be useful for miniupnp users, therefore I'm creating this pull request with iptables match rules for miniupnp project. Feel free to move it or drop if you think it is not useful at all.
Detailed description is available on:
https://serverfault.com/a/911286
https://unix.stackexchange.com/a/444804
> miniupnpc: Add information about iptables settings into README

- miniupnpd/Makefile.linux_nft
- miniupnpd/netfilter_nft/nftnlrdr.c
- miniupnpd/netfilter_nft/nftnlrdr_misc.c
- miniupnpd/netfilter_nft/nftnlrdr_misc.h
Trying my hand at getting nftables support up to speed.
In libnftnl versions >=1.0.7 a lot of [aliases and compat were removed](https://git.netfilter.org/libnftnl/commit/?id=907a9f8e5a93f5bcd449643eb3916a656d634758) breaking miniupnpd's nftables support completely. I've fixed all the errors caused by this I'm aware of. Not sure if there's some warnings too that should be fixed.
What's currently missing is writing the update_portmapping and update_portmapping_desc_timestamp functions for the nftables backend as done for others in bdac007. Though I doubt I've got the code-fu to do that.
> miniupnpd: support newer libnftnl versions

- miniupnpc/msvc/miniupnpc.vcxproj
- miniupnpc/msvc/miniupnpc.vcxproj.filters
declspec.h was renamed to miniupnpc_declspec.h but the MSVC file reference was not updated.
Thanks,
Brett
> Update renamed file in MSVC Project

- miniupnpc/minissdpc.c
Everything should still work with Windows XP as minimum version.
Those API are, according to Microsoft docs, compatible with XP.
This is in relation to #238 and godotengine/godot#22044 godotengine/godot#20672 .
Replaces `GetBestRoute` with [`GetBestInterfaceEX`](https://docs.microsoft.com/en-us/windows/desktop/api/iphlpapi/nf-iphlpapi-getbestinterfaceex) .
Replaces `GetIpAddrTable` with [`GetAdaptersAddresses`](https://docs.microsoft.com/en-us/windows/desktop/api/iphlpapi/nf-iphlpapi-getadaptersaddresses).
I know you mentioned that UWP has it's own API for UPNP, but many software, like Godot Engine, uses this library due to its great platform support, and I felt it was a pity that we had to make an UWP specific implementation of that.
Let me know what you think, I hope this helps :)
> Replace GetBestRoute and GetIpAddrTable with UWP-compatible API

- miniupnpc-async/miniupnpc-async.c
- miniupnpc-async/parsessdpreply.c
- miniupnpc-libevent/miniupnpc-libevent.c
- miniupnpc/minissdpc.c
I stumbled upon this when reading through the SSDP reply parsing code. I don't know if any real world devices send SSDP reply headers that start with `st`, `location`, or `usn` without being an exact match, but it seems good to handle that possibility correctly nonetheless.
> Ensure SSDP reply headers are not partial matches

- miniupnpd/Makefile.linux
Add basic security compilation flags for miniupnpd Linux compilation, to mitigate memory corruption and other attacks
This is useful when using old compilers, cross-compilers or even just non-x86 compilers, as those are not configured to add these flags by default
I believe the same flags should work as-is for the BSD makefile as well, but I haven't tested it
> miniupnpd: add secure compilation flags for Linux

- miniupnpd/Makefile.linux_nft
When build with nft, copy nft scripts rather than iptables scripts.
> miniupnpd: Install nftables scripts

- miniupnpd/portinuse.c
Structures xtcpcb and xinpcb returned by the kernel
hide now part of its members after r315662. The fix
was inspired by changes made in usr.bin/systat/netstat.c
tool.
> Update portinuse code to reflect changes made in FreeBSD 12.0

- miniupnpc/connecthostport.c
Calling `closesocket()` will result in Winsock internally calling `WSASetLastError(0)`, which wipes out the original error from the `connect()` call that we're trying to print with `PRINT_SOCKET_ERROR("connect")`. 
This results in stderr output like the following when connection errors occur while searching for devices:
```
Socket error: connect, 0
Socket error: connect, 0
Socket error: connect, 0
```
With some slight changes to the loop, we can avoid this situation and get the proper error codes:
```
Socket error: connect, 10060
Socket error: connect, 10060
Socket error: connect, 10060
```
> Fix connect() socket error trace on Windows

- miniupnpc/CMakeLists.txt
In some cases (such as using the library via `add_subdirectory` in CMake), it may be desirable to disable installation.
> [CMake] Add UPNPC_NO_INSTALL option

- appveyor.yml
- miniupnpc/Makefile.mingw
- miniupnpc/setupmingw32.py
I reworked the Appveyor build process and introduced the following changes :
- The python module is built for Python 2.7 (as before), Python 3.5 and Python 3.7. Adding support for new python versions should be relatively easy.
- The python module is distributed both as a raw egg file (which existed previously but was buried in a zip file with other non-required binary files), and a wheel file (which seems to be the recommended distribution method for python modules now).
- I only tested the .egg and .whl files for Python 3.7 under Windows 7 32 bits, which is the environment I was interested in. The other builds completed without errors but may require further validation.
- One of the main fixes that allowed the Python 3 versions to build was to remove the --compiler directive given to …
> Fixing the Upnpc delivery process for windows targets

- miniupnpd/Changelog.txt
- miniupnpd/minissdp.c
If several different interfaces share same ipv4 address on different subnets (i.e. eth0 192.168.1.1/24 + eth1 192.168.1.1/16), miniupnpd may pick any one of them, possibly wrong one w/o respecting exact
listening_ip interface.
syslog will contain something similar to:
miniupnpd: sendto(udp_notify=6, 192.168.1.1): No such device
miniupnpd: sendto(udp_notify=6, 192.168.1.1): No such device
miniupnpd: try_sendto(sock=6, len=464, dest=239.255.255.250:1900): sendto: No such device
miniupnpd: try_sendto(sock=6, len=464, dest=239.255.255.250:1900): sendto: No such device
miniupnpd: try_sendto failed to send 11 packets
Fix that with specifying exact outgoing mcast interface for  notify socket with help of IP_MULTICAST_IF/mreqn struct.
Since OpenAndConfSSDPNotifySocket() now takes lan_addr_s …
> miniupnpd: fix ssdp notify on unrelated interfaces

- miniupnpc/upnperrors.c
According to the specification
http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v2-Service.pdf, the
708 error code corresponds to InvalidLayer2Address. Also
WildcardNotPermittedInSrcIP is for 715 which is already properly mapped.
> Fix error code for 708

- miniupnpd/netfilter_nft/scripts/nft_init.sh
- miniupnpd/netfilter_nft/scripts/nft_removeall.sh
Rework nft_removeall.sh to preserve nftables structures that miniupnpd didn't add. Important for firewalld and sshguard co-existance.
> Rework nft_removeall.sh to preserve other nftables structures

- miniupnpd/Makefile.linux
- miniupnpd/Makefile.linux_nft
- miniupnpd/genconfig.sh
- miniupnpd/linux/ifacewatcher.c
- miniupnpd/netfilter_nft/nftnlrdr_misc.c
A couple seem intentional (linux/ifacewatcher.c). Most look like they were unintentionally omitted (netfilter_nft/nftnlrdr_misc.c).
Resubmitted without unintended indentation changes included in previous pull request.
> Update case statements to fix compiler 'fall through' warnings

- miniupnpc/CMakeLists.txt
- miniupnpc/minissdpc.c
- miniupnpc/portlistingparse.c
These changes shouldn't conflict with anything, and I don't expect the rename of atoui to atoui2 to affect other systems. (On Haiku, atoui was already defined in stdlib)
> Add Haiku Support

- miniupnpd/INSTALL
- miniupnpd/pf/obsdrdr.c
`v4` in pfvar.h is changed to `v4addr` after xnu 4570.1.46
> fix build for macos

- miniupnpc/testupnpigd.py
fix: TypeError: a bytes-like object is required, not 'str'
*write function's parameter type is bytes.
> fix: TypeError: a bytes-like object is required, not 'str'

- appveyor.yml
- miniupnpc/Makefile.mingw
- miniupnpc/miniupnpc.def
* Ensure that all executables would have .exe Windows extension
* Do not use dll subdirectory, so makefile would be slash agnostic
* Define common targets to simplify makefile
* Export required functions for listdevices executable
Fixes: https://github.com/miniupnp/miniupnp/issues/428
> Fix and simplify Makefile.mingw for miniupnpc

- miniupnpd/netfilter/iptcrdr.c
In delete_redirect_and_filter_rules() found a typo error
in update_portmapping() we have to update snat rules
and it is reasonable to ignore the failure if no snat rule found
> miniupnpd: typo fix and update snat rules

- miniupnpd/Changelog.txt
- miniupnpd/minissdp.c
So we don't answer with the v6 LOCATION to v4 clients anymore !
should fix #467
see #461
> miniupnpd: fix processing of v4 M-SEARCH received on v6 socket

- miniupnpc/connecthostport.c
- miniupnpc/minisoap.c
- miniupnpc/minissdpc.c
- miniupnpc/miniupnpc.c
- miniupnpc/miniwget.c
- miniupnpc/setupmingw32.py
- miniupnpc/upnpc.c
_snprintf() differs from snprintf() in:
* on overflow it returns -1 instead of required buffer size
* on overflow it does not fill nul byte
* does not accept NULL/0 as a buffer
Microsoft implemented snprintf() in Visual Studio 2015 as part of UCRT.
Mingw32 contains snprintf() implementation only when __USE_MINGW_ANSI_STDIO
is defined.
Mingw-w64 versions prior to 8.0.0. contain snprintf() implementation when
__USE_MINGW_ANSI_STDIO or _UCRT is defined. Since version 8.0.0 it is
always supported.
Mingw-w64 defines both __MINGW32__ and __MINGW64_VERSION_MAJOR macros.
Mingw32 defines only __MINGW32__.
_scprintf() just count number of bytes needed for formatting string, so it
is basically return value of snprintf().
This change updates miniupnpc code to use snprintf() when is provided by …
> miniupnpc: Fix usage of Windows _snprintf() function

- miniupnpc/upnpc.c
Allow to use such IGD devices by new -i option.
> miniupnpc: By default skip invalid, disconnected and non-IGD devices

- miniupnpd/Changelog.txt
- miniupnpd/configure
- miniupnpd/portinuse.c
all CIRCLEQ have been replaced by TAILQ
fixes #496
> fix portinuse.c for OpenBSD 5.5+

- miniupnpc/connecthostport.c
- miniupnpc/minisoap.c
- miniupnpc/minissdpc.c
- miniupnpc/miniupnpc.c
- miniupnpc/miniwget.c
- miniupnpc/upnpc.c
- miniupnpc/win32_snprintf.h
* Move it into separate win32_snprintf.h file to de-duplicate its
implementation from all miniupnp source files.
* Do not use this emulation with mingw32 SDK when __NO_ISOCEXT is not
defined as in this case mingw32 provides working snprintf function.
* Fix detection for mingw-w64 variants, when __NO_ISOCEXT is defined or
when older version without UCRT is used.
* Add check if _scprintf function is available. In case it is not available
just returns length of filled buffer to prevent buffer overflow.
> Fix snprintf emulation for Windows

- miniupnpc/Makefile
I guess it's expected people do `#include <miniupnpc/upnpcommands.h>` not `#include <upnpcommands.h>`, right?
> miniupnpc.pc: remove "miniupnpc" from includedir

- miniupnpc/CMakeLists.txt
- miniupnpc/miniupnpc-config.cmake
I have included all the commits here because there would be merge conflicts otherwise.
CMake usually only builds shared or static, not both. So there isn't really a standard way, but I went for the miniupnpc::miniupnpc alias library which alias the static or shared library based on a MINIUPNPC_USE_STATIC_LIBS variable. The use of XXX_USE_STATIC_LIBS exists on some of the FindXXX modules that come with cmake.
> Install cmake config file

- miniupnpd/commonrdr.h
- miniupnpd/ipf/ipfrdr.c
- miniupnpd/pf/obsdrdr.c
There is a small typo in miniupnpd/commonrdr.h, miniupnpd/ipf/ipfrdr.c, miniupnpd/pf/obsdrdr.c.
Should read `description` rather than `decription`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, decription -> description

- miniupnpc/addr_is_reserved.c
- miniupnpc/minissdpc.c
When struct ip_mreqn is passed to IP_MULTICAST_IF setsockopt option it is
always required to set also ipv4 source address. Otherwise Linux kernel
will choose default system multicast ipv4 address which does not have to
belong to chosen interface specified in struct ip_mreqn.
Therefore on system with more multicast interfaces and more ipv4 addresses,
it may happen that interface chosen by upnpc -m option would use ipv4
address which does not belong to this interface.
This change is fixing above issue and ensure that if interface is chosen by
upnpc -m option then source address which belongs to this interface would
be used.
Without this change upnpc -m eth1 can send multicast traffic over interface
eth1 but with source ipv4 address of interface eth0, which obviously would
be rejected by …
> miniupnpc: Fix usage of IP_MULTICAST_IF with struct ip_mreqn

- miniupnpc/minissdpc.c
Horrifying hack to get it linking on Windows UWP.
Seems the declaration of `in6addr_any` exists in Windows UWP headers but not the definition so it fails to link. So I substitute with an equivalent definition.
> Fix Windows UWP build.

- miniupnpc/addr_is_reserved.c
- miniupnpc/minissdpc.c
Since #499, `GetBestInterface` is used instead of `GetBestInterfaceEx` for compatibility with old mingw verisons (and because IPv6 is indeed not needed), but microsoft decided for no apparent reason beside pure lobbying not to include the IPv4-only version `GetBestInterface` in the UWP libraries.
This PR reintroduces the use of `GetBestInterfaceEx` while trying to keep compatibility with old mingw by checking the `_WIN32_WINNT`, which I've also switched to use the [well known code](https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-160) instead of `_WIN32_WINNT_VISTA` which might not be defined.
> Fix UWP builds after mingw changes

- miniupnpc/upnpc.c
- miniupnpd/upnpsoap.c
IGD v2.0 specification for WANIPConnection:2 says:
When the external IP address could not be retrieved by the gateway (for
example, because the interface is down or because there was a failure in
the last connection setup attempt), then the ExternalIPAddress MUST be
equal to the empty string.
> IGD v2.0: Unknown ExternalIPAddress is represented as empty string

- miniupnpc/minissdpc.c
`clock_gettime` is only available on macOS >= 10.12, iOS >= 10.0 (etc).
Support compiling with a MACOSX_DEPLOYMENT_TARGET < 10.12 by using `__builtin_available` to detect when running on an earlier system, and fall-back to `gettimeofday` when `clock_gettime` is not available.
> Fallback for earlier Apple platforms that lack clock_gettime

- miniupnpc/CMakeLists.txt
Currently, `listdevices.c` is included in `MINIUPNPC_SOURCES`, and thus it is included / built as part of the `libminiupnpc-static` & `libminiupnpc-shared` library targets.
This can cause issues with certain build systems / targets. (I.e. Potentially overriding `main` for an executable that links to `libminiupnpc-static`, depending on a number of factors.)
@miniupnp
> [CMake] Only include listdevices.c as part of the listdevices executable

- miniupnpc/upnpdev.h
Note that `__STDC_VERSION__` version checks are currently performed 3 different ways in this codebase. Not sure if you want to consolidate how they are done? The other two being:
https://github.com/miniupnp/miniupnp/blob/7783ac1545f70e3341da5866069bde88244dd848/miniupnpc/miniupnpctypes.h#L10
https://github.com/miniupnp/miniupnp/blob/2254e8928e658e7f65418bec1efcaa055946f123/miniupnpd/netfilter_nft/nftnlrdr_misc.c#L52
> Fix `__STDC_VERSION__` check in upnpdev.h

- .github/workflows/i586-mingw32msvc.yml
- .github/workflows/i686-w64-mingw32.yml
- .github/workflows/x86_64-w64-mingw32.yml
Add support for i586-mingw32msvc and x86_64-w64-mingw32 cross-compilers into Github CI like it was in old Travis CI.
> Extend GitHub workflows for Windows

- miniupnpd/miniupnpd.c
Improve error message so users don't need read the source to figure out
why miniupnpd refuses to start even if the usage is correct.
> miniupnpd: improve error message for bad config

- miniupnpd/miniupnpd.c
Obviously port forwarding cannot work when upstream interface is down. So
correctly report status code for port forwarding requests to clients in
this case.
> miniupnpd: Disable port forwarding when upstream interface is down

- miniupnpd/miniupnpd.c
- miniupnpd/options.c
- miniupnpd/options.h
- miniupnpd/upnpglobalvars.c
- miniupnpd/upnpglobalvars.h
- miniupnpd/upnppinhole.c
- miniupnpd/upnppinhole.h
This patch adds a lease file for IPv6 pinholes.
The leases are maintained and readded when miniupnpd restarts.
Currently all IPv6 leases are lost on restart.
There is an open request for #18 
Please let me know if there should be any changes.
Best
Sven
> IPv6 pinholes lease file

- miniupnpd/Makefile.linux
Test that ldd is from GLIBC before exctracting the GLIBC_VERSION. This
is not needed with musl libc.
> miniupnpd: don't check for glibc version with musl

- miniupnpd/testgetifaddr.sh
Fixes `testgetifaddr.sh` test failures in two situations:
1. when there is no default route.
2. when the tested interface has more than one IP address.
> Fix testgetifaddr.sh for less common network environments

- miniupnpc/Makefile
Fix missing references to $(BUILD) in the install rules, as well
as incorrect shared library symlink name.  Otherwise, the 'install'
phase fails either being unable to find files:
make: *** No rule to make target 'miniupnpc.pc', needed by 'install'.  Stop.
or trying to create the symlink in the wrong subdirectory:
ln: failed to create symbolic link '/tmp/z/usr/lib/build/libminiupnpc.so': No such file or directory
> Makefile: fix install rules to account for $(BUILD)

- miniupnpc/CMakeLists.txt
Install target fails as include files have moved
```
"build/miniupnpc-2.2.3/miniupnpc.h":
No such file or directory.
FAILED: CMakeFiles/install.util 
cd build/miniupnpc-2.2.3/.x86_64-libreelec-linux-gnu && toolchain/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```
> miniupnpc/CMakeLists.txt: fix install for headers

- miniupnpd/netfilter_nft/nftnlrdr.c
- miniupnpd/netfilter_nft/nftnlrdr_misc.c
- miniupnpd/netfilter_nft/scripts/nft_delete_chain.sh
- miniupnpd/netfilter_nft/scripts/nft_display.sh
- miniupnpd/netfilter_nft/scripts/nft_flush.sh
- miniupnpd/netfilter_nft/scripts/nft_init.sh
- miniupnpd/netfilter_nft/scripts/nft_removeall.sh
NFTables supports inet in the nat chain as well.
Use it instead of IPv4 chain so it is consistent with the filter chain.
This also removes the need for two separate tables to manage.
This is the linked to #422 and the first commit to fix it.
Signed-off-by: Sven Auhagen <sven.auhagen@voleatech.de>
> NFTables use inet nat chain

- miniupnpd/miniupnpd.conf
- miniupnpd/netfilter_nft/README.md
- miniupnpd/netfilter_nft/nftnlrdr.c
- miniupnpd/netfilter_nft/nftnlrdr_misc.c
- miniupnpd/netfilter_nft/scripts/miniupnpd_functions.sh
- miniupnpd/netfilter_nft/scripts/nft_delete_chain.sh
- miniupnpd/netfilter_nft/scripts/nft_display.sh
- miniupnpd/netfilter_nft/scripts/nft_flush.sh
- miniupnpd/netfilter_nft/scripts/nft_init.sh
- miniupnpd/netfilter_nft/scripts/nft_removeall.sh
To hardcode table and chain creation and deletion makes it impossible
for existing firewall infrastructures to integrate miniupnpd.
NFTables will either reevaluate packets through miniupnpd or
it will delete existing tables when there are already custom chains in it.
This commit will use the scripts to create the tables and chains, to make nftables
work the same way as iptables does.
Signed-off-by: Sven Auhagen <sven.auhagen@voleatech.de>
> NFTables use scripts to create tables and chains

- miniupnpc/Makefile.mingw
Adds support for generating a miniupnpc.pc file to Makefile.mingw. Essentially the same as is done in the other Makefile.
> mingw: add minimal pkg-config support

- miniupnpc/CMakeLists.txt
As with `_CRT_SECURE_NO_WARNINGS`, this change hides some warnings:
```
[...]\miniupnp\miniupnpc\src\addr_is_reserved.c(60): warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
[...]\miniupnp\miniupnpc\src\minissdpc.c(603): warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
[...]\miniupnp\miniupnpc\src\minissdpc.c(753): warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
```
> miniupnpc/cmake: add _WINSOCK_DEPRECATED_NO_WARNINGS definition

- miniupnpc-async/minixml.c
- miniupnpc/src/minixml.c
- miniupnpd/minixml.c
In the commit a0573e251817ec090a8c9f9f41b56d720c835a6c
was fixed a buffer overflow in the minixml.c but it wasn't copied to upnpc-async.
To make comparison simpler the header was also synced from miniupnpc-libevent/minixml.c
Also please note that there is other files that were copied between projects but now differs:
* minissdpd/upnputils.c
* miniupnpc-async/upnputils.c
* miniupnpd/upnputils.c
It's possible that a bug fixed in one place wasn't copied to another.
> minixml.c sync sources

- miniupnpd/configure
- miniupnpd/getifaddr.c
This PR contains two commits for your consideration:
- The first commit introduces a new `--getifaddrs` flag in the `configure` script and enables `getifaddrs()` usage by default for OpenWrt
- The second commit adjusts the `getifaddrs()` based implementation of `getifaddr()` to prefer non-reserved IPv4 addresses over reserved ones
> Expose `USE_GETIFADDRS` and tweak `getifaddr()` behaviour

- miniupnpc/updateminiupnpcstrings.sh
On NixOS, the lsb_release command returns strings such as "NixOS"
and "22.04" (with the quotes included). This leads to compilation
problems because the updateminiupnpcstrings.sh scripts ends up
creating a C file with the following content:
The fix is to simply strip the quotes from the lsb_release output.
> Fix the build on NixOS

- miniupnpc/Makefile.mingw
Otherwise it'll be left over after a `make clean`.
> build: add distfile to miniupnpc make clean target

- miniupnp.podspec
It's not clear to me why this is pointing to a fork of this repository (which has been marked as archived for nearly 3 years).
I guess this can be updated to point to this repo, or the podspec removed entirely if there is no interest in maintaining it?
> podspec: point to miniupnp/miniupnp repo

- miniupnpc/CMakeLists.txt
It is not the job of a generic build script to decide which version(s) of an OS we are compiling for.
> miniupnpc: allow _WIN32_WINNT override

- miniupnpc/src/minissdpc.c
No room allocated for end of strings ("\0")
> minissdpc.c: fix memory allocation error

- miniupnpc/src/upnpc.c
SpecifiedArrayIndexInvalid when listing port mappings with -l.
> upnpc: Do not show the normally occurring error 713

- miniupnpd/pf/obsdrdr.c
- miniupnpd/pf/pfpinhole.c
Fixes a change made in pf on OpenBSD 7.4 where one needs to now call `DIOCXEND` for every call to `DIOCGETRULES`. There is now a finite number of tickets, and exceeding this just results in a 'Device busy' error when calling `DIOCGETRULES`. Without this fix, miniupnpd gets to a state where it cannot add/remove any rules.
Here's the relevant part from the 7.4 changelog:
```
Speed up the ioctl(2) request DIOCGETRULE such that pfctl(8)
can retrieve all pf(4) rules from the kernel in linear rather than
in quadratic time. To protect the kernel from memory exhaustion,
userland processes now have to release tickets obtained with
DIOCGETRULES by issuing the new ioctl(2) request DIOCXEND.
In particular, snmpd(8) and systat(1) now do that.
```
> Fix for OpenBSD 7.4

- miniupnpc-async/miniupnpc-async.c
- miniupnpc-libevent/miniupnpc-libevent.c
and user-agent also in asynchronous sample code. The commits https://github.com/miniupnp/miniupnp/commit/a6aa3711668247c660699cd285d5bfffaa739324 and https://github.com/miniupnp/miniupnp/commit/b557fdf4db713aee838669970bad02498a1c5d86 were incomplete.
Field value MUST be "text/xml; charset="utf-8"".
Field value MUST be "text/xml; charset="utf-8"" for description documents.
https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v1.1.pdf
> miniupnpc: Fix UPnP UDA 1.1 content-type charset compliance

- miniupnpc/src/upnpc.c
Control points that have not been authenticated and authorized as defined in IGDv2 SHOULD use their
IPv6 GUA when calling this action.
http://upnp.org/specs/gw/UPnP-gw-WANIPv6FirewallControl-v1-Service.pdf
> upnpc: Show hint to use IPv6 (option -6) for pinhole commands

- .github/actions/activate-venv/action.yml
- .github/actions/activate-venv/activate_venv.py
- .github/actions/activate-venv/readme.md
- .github/actions/activate-venv/test_check_activated.py
- .github/actions/create-venv/action.yml
- .github/actions/create-venv/create_temporary_venv.py
- .github/actions/create-venv/readme.md
- .github/actions/readme.md
- .github/workflows/miniupnpc_wheels.yml
This adds wheel building CI in GitHub Actions for all operating systems and platforms except for Windows ARM. 
This was requested in https://github.com/miniupnp/miniupnp/issues/616.  You can see builds in my fork at https://github.com/altendky/miniupnp/pull/1 as long as they aren't being run here.
Draft for:
- I would suggest not worrying about this at the moment.  It's not clear that we can properly create the old style presently and projects like `coverage` are using new-style only.  If really needed, maybe we can just do a file copy to the legacy naming style to get them.
> build miniupnpc wheels in ci

- miniupnpc/CMakeLists.txt
I think those executable targets should remain in `if(UPNPC_BUILD_SAMPLE)`.
> cmake: don't add executable targets when `UPNPC_BUILD_SAMPLE` is `OFF`

- .github/workflows/miniupnpc_wheels.yml
This avoids automatic GHA warnings such as shown in the annotations at https://github.com/miniupnp/miniupnp/actions/runs/8257740388?pr=717.  Except that, as it turns out, that specific error comes out of the https://github.com/actions/setup-python action.  But still, probably good to be updating pip.
> update pip for wheel build

- miniupnpc/src/win32_snprintf.h
The check for `snprintf` support is currently broken, as it fails to handle all documented cases. Specifically, `snprintf` is needlessly emulated for the following scenarios:
- mingw-w64 6.0.0 or new with ucrt
- mingw-w64 8.0.0 or new with iso c ext
For more details, please refer to https://godbolt.org/z/ov3oGj9sz.
This PR resolves the issue and can be verified using https://godbolt.org/z/fWzMT5TeW.
> Fix macro expression that guards `snprintf` for Windows

- miniupnpc/src/upnpc.c
Add -f option to delete multiple port redirections.
Use -d to delete batch of port redirections is too slow.
> upnpc: Add -f option to delete multiple port redirections

- .github/workflows/miniupnpc_wheels.yml
github recently swapped macos-latest to 14 on arm
> intel: [macos-12]

- miniupnpc/CMakeLists.txt
The `TYPE` argument for `install(FILES)` is added in CMake 3.14.
https://github.com/miniupnp/miniupnp/blob/ae311e4b84e3dc3cbc9a6559774f2109705967ac/miniupnpc/CMakeLists.txt#L313-L315
https://cmake.org/cmake/help/latest/release/3.14.html
https://cmake.org/cmake/help/latest/command/install.html#files
> miniupnpc: bump CMake version to 3.14

- .github/workflows/miniupnpc_wheels.yml
PyPA has provided a specific action for uploading to PyPI.  https://github.com/pypa/gh-action-pypi-publish  It can be used in various ways but my understanding is that the trusted publisher mode is preferred.  Instructions for the 'authorization' setup are provided at https://docs.pypi.org/trusted-publishers/adding-a-publisher/.
Draft for:
> add pypa/gh-action-pypi-publish

- miniupnpd/Makefile.linux
- miniupnpd/Makefile.linux_nft
- miniupnpd/configure
Chimera linux is a linux distribution with musl libc and BSD userland.  This series of commits make small adjustments to let miniupnpd to build on it.
> miniupnpd: Fix build on Chimera linux

- miniupnpc/src/upnpc.c
Introduced in https://github.com/miniupnp/miniupnp/commit/c0a50ce33e3b99ce8a96fd43049bb5b53ffac62f
> Fix typo 'unsed' -> 'unset'

- miniupnpd/minissdp.c
- miniupnpd/pcpserver.c
Bind ipv6 socket to the interface to completely solve the threat of directional attacks caused by WAN port scanners and leaked IPs
> miniupnpd: bind ssdp notify and pcp with v6 to device

- miniupnpc/src/upnpcommands.c
Visual Studio shows squiggly underlines for every `sscanf` in this file - because the returned value was ignored.
This should fix two issues:
- the value assigned to an _out_ parameter before a call may change even if the call failed;
- if nothing was read, proper error code should be returned.
> Verify sscanf return code

- miniupnpd/miniupnpd.c
- miniupnpd/miniupnpd.conf
- miniupnpd/natpmp.c
- miniupnpd/options.c
- miniupnpd/options.h
- miniupnpd/testgetifaddr.c
- miniupnpd/testportinuse.c
- miniupnpd/upnpdescgen.c
- miniupnpd/upnpglobalvars.h
- miniupnpd/upnpredirect.c
- miniupnpd/upnpsoap.c
In case that router getting private IP but upstream server has full-cone NAT enabled, current full-cone NAT detect mechanism would make miniupnpd stop working. So add force_forwarding option to let user optionally force bypassing this mechanism.
This PR should close https://github.com/miniupnp/miniupnp/issues/785 https://github.com/miniupnp/miniupnp/issues/705
> miniupnpd: Add ignore_private_ip option

- miniupnpd/Changelog.txt
- miniupnpd/miniupnpd.c
- miniupnpd/miniupnpd.conf
- miniupnpd/natpmp.c
- miniupnpd/options.c
- miniupnpd/options.h
- miniupnpd/upnpdescgen.c
- miniupnpd/upnpglobalvars.h
- miniupnpd/upnpsoap.c
Currently we are using a mix of "ignore private ip" and "ignore private ip check" in code. Let's unify them to "ext ignore private ip check". We always use private ip in most cases for internal interfaces, and it would be confusing if we don't use ext prefix.
Besides, full-cone NAT, which is also named as endpoint-independent NAT in some IETF RFC document. Add this name and a source of it to miniupnpd.conf.
> miniunpnpd: Unify naming scheme and rename to ext_ignore_private_ip_check for ignore_private_ip_check

- miniupnpd/Makefile.bsd
- miniupnpd/Makefile.macosx
- miniupnpd/Makefile.sunos
- miniupnpd/testportinuse.c
testportinuse build fails because proto_itoa() is moved to upnputils.c but the make rule is not updated in Makefile.bsd.
Also update Makefile.macosx and Makefile.sunos since it looks that they require the same fix.
> miniupnpd: fix testportinuse build on bsd with the --portinuse configure option

- miniupnpc/src/connecthostport.c
Follow up on #830.
The analyser is a bit confused that in one place we compare `while(n < 0)` and in the other we compare `if(n == -1)`. This results in the analyser believing there are situations where n would be less than -1.
The solution to silence this false positive is to adopt the same comparison consistently: either `n < 0` in both places or `n == -1` in both places.
(or to set `errno = err` unconditionally but that has already been rejected in my previous PR)
> fix: An undefined value may be read from 'errno'

- miniupnpc/src/addr_is_reserved.c
- miniupnpc/src/connecthostport.c
- miniupnpc/src/minisoap.c
- miniupnpc/src/minissdpc.c
- miniupnpc/src/miniupnpc.c
- miniupnpc/src/miniwget.c
- miniupnpc/src/receivedata.c
As MS tells, this "can reduce the size of the Windows header files by excluding some of the less common API declarations".
> Add WIN32_LEAN_AND_MEAN.

- miniupnpc/include/miniupnpc.h
Just a documentation warning fix.
> miniupnpc: Empty paragraph passed to '\param' command

- miniupnpc-async/miniupnpc-async.c
Xcode analyser warning.
This is roughly the same as 2fd247b.
> miniupnpc-async: locationsize is an uninitialized value

- miniupnpd/pcpserver.c
Fix an Xcode analyser warning:
> miniupnpd: Value stored to 'remain' is never read

- minissdpd/minissdpd.c
> minissdpd: Value stored to 's_ssdp' is never read
