miniupnp/miniupnp

miniupnpc/upnpc.c

As discussed https://github.com/miniupnp/miniupnp/issues/104#issuecomment-95973663 and https://github.com/miniupnp/miniupnp/issues/104#issuecomment-95973663

add optional parameter <external_port> to option -r

---

miniupnpd/genconfig.sh
miniupnpd/linux/getifstats.c
miniupnpd/miniupnpd.c
miniupnpd/upnphttp.c

Please excuse the github noobness.  This PR was to contain only the changes to miniupnpd.c, however I have clearly not done it properly, and as such it also contains the contents of PR #123 
This second PR adds the changes that Tomato makes to miniupnpd.c exactly as found in Tomato Shibby and Toastman builds, however simply wrapped in #ifdef TOMATO.
This PR if merged will allow very simple merging of all upstream changes into Tomato, as all codebase will be fully in sync with upstream.

Minor Changes Proposed to Allow Easier Merge of Upstream to Tomato #2

---

miniupnpd/genconfig.sh

Define "TOMATO" in Tomato portion of config file creation

Define "TOMATO" in Tomato portion of config file creation

---

miniupnpd/getifaddr.c
miniupnpd/minissdp.c
miniupnpd/upnpsoap.c

Fix some insecure code, please review it.

Various fix

---

.travis.yml

... also for fixing the issue you mentioned in https://github.com/miniupnp/miniupnp/pull/127#issuecomment-140402275.
See: http://docs.travis-ci.com/user/customizing-the-build/#Excluding-Builds

Some TravisCI improvements

---

README
appveyor.yml

I removed the single quotes if you don't mind.

Fix appveyor builds

---

miniupnpc/upnpc.c

RemoveRedirect() now return an error code

---

miniupnpc/LICENSE

Simply updated copyright notice.

2015 => 2016

---

miniupnpc/testupnpigd.py

Add python 3 compatibility to IGD test.

Add python 3 compatibility to IGD test

---

miniupnpc/upnpc.c

AddPortMapping() now returns -2 on failure.

AddPortMapping() now returns an error code

---

miniupnpc/MANIFEST.in

cli:py: do not ship binaries in sdist

---

miniupnpc/connecthostport.c
miniupnpc/minisoap.c
miniupnpc/minissdpc.c
miniupnpc/miniupnpc_socketdef.h

Move common definition to miniupnpc_socketdef.h

---

miniupnpd/netfilter_nft/nftnlrdr.c
miniupnpd/netfilter_nft/nftnlrdr.h

Fix compilation with nftables

---

miniupnpd/minissdp.c

similar to commit 9fcc0a72f09e6e1aa46ddcc997d3dcae87d4b416

avoid off-by-one buffer overread

---

miniupnpc-libuv/README
miniupnpc-libuv/codelength.h
miniupnpc-libuv/example.c
miniupnpc-libuv/minissdpc-libuv.c
miniupnpc-libuv/minissdpc-libuv.h
miniupnpc-libuv/miniupnpc_declspec.h
miniupnpc-libuv/upnpdev.h

Here is a quick&dirty but working implementation of the minissdp client with libuv to have an asynchronous client.
What do you think about it? Mergeable? Useful?

minissdpc: add a libuv client

---

miniupnpc/miniupnpcmodule.c

This parameter was already present in the C API but not exposed to the
python module.
For backward compatibility, leaseDuration was made optional with a
default value of 0 (unlimited duration).

Added the leaseDuration parameter to the addportmapping python binding.

---

miniupnpd/netfilter_nft/nftnlrdr.c
miniupnpd/netfilter_nft/nftnlrdr_misc.c
miniupnpd/netfilter_nft/scripts/nft_delete_chain.sh
miniupnpd/netfilter_nft/scripts/nft_display.sh
miniupnpd/netfilter_nft/scripts/nft_flush.sh
miniupnpd/netfilter_nft/scripts/nft_init.sh
miniupnpd/netfilter_nft/scripts/nft_removeall.sh

This commit fixes the list detection and uses the inet chain for ipv4.
The scripts got reworked as well and a display script was added.

NFTables fixes and scripts

---

miniupnpd/netfilter_nft/nftpinhole.c

This PR fixes some issues with nftables pinholes.
It adds some extra checks for empty source addresses, fixes ports and the update pinhole function had a logical error where the uid was changed.

nftables pinhole fixes

---

miniupnpd/genconfig.sh

Upstream-Status: Pending
Signed-off-by: Khem Raj <raj.khem@gmail.com>

Add OpenEmbedded cross compile case

---

miniupnpd/Makefile.linux
miniupnpd/netfilter/Makefile

Correct typo

---

miniupnpd/upnpstun.c

This pull request fixes STUN debug/testing application and improve logging.
I tested this change with following STUN servers and it parsed all received fields:
stun.stunprotocol.org
stun.sipgate.net
stun.ekiga.net
stun.xten.com
stun.onesuite.com

STUN changes

---

appveyor.yml

Appveyor python 64b

---

.travis.yml
miniupnpd/Changelog.txt
miniupnpd/Makefile.linux_nft
miniupnpd/Makefile.macosx
miniupnpd/linux/getifstats.c
miniupnpd/miniupnpd.c
miniupnpd/netfilter/iptpinhole.c
miniupnpd/netfilter_nft/nftnlrdr.c
miniupnpd/netfilter_nft/nftnlrdr_misc.c
miniupnpd/netfilter_nft/nftpinhole.c

support linux capabilities (libcap or libcap-ng)
fixes #405

Capabilities

---

miniupnpd/netfilter_nft/nftnlrdr.c
miniupnpd/netfilter_nft/nftnlrdr_misc.c
miniupnpd/netfilter_nft/nftnlrdr_misc.h

fixes in netfilter_nft

---

miniupnpd/pf/Makefile
miniupnpd/pf/obsdrdr.c
miniupnpd/pf/obsdrdr.h
miniupnpd/pf/testobsdrdr.c
miniupnpd/pf/testpfpinhole.c

still to be done : 
* error checking
* removal of `nat` rule

pf nat rules

---

miniupnpc/miniupnpc.c

Check for 0.0.0.0, 192.168., 10. and 172. is not enough. Nowadays routers
behind NAT are getting IP address from shared CG-NAT space 100.64.0.0/10.
This patch adjust miniupnpc to check for all reserved IPv4 addresses.

Fix check for reserved IP addresses in miniupnpc

---

.travis.yml
miniupnpc/addr_is_reserved.c
miniupnpc/minissdpc.c

Add also i586-mingw32msvc-gcc cross-compile builds to Travis CI.

Fix compilation with i586-mingw32msvc-gcc compiler

---

.travis.yml

Travis YAML file cannot be currently parsed and therefore Travis was not started, see:
https://travis-ci.org/github/miniupnp/miniupnp/requests

Fix syntax error in Travis YAML file

---

miniupnpd/miniupnpd.c

There is missing corner case check when these functions return failure.
Network in this case does not work, so disable port forwarding to prevent
returning incorrect response about port forwarding state.
Also explicitly set disable_port_forwarding to 0 on success to make code
more readable.

miniupnpd: Add some missing checks when update_ext_ip_addr_from_stun() or getifaddr() fails

---

miniupnpd/miniupnpd.conf
miniupnpd/netfilter_nft/README.md
miniupnpd/netfilter_nft/scripts/miniupnpd_functions.sh
miniupnpd/netfilter_nft/scripts/nft_delete_chain.sh
miniupnpd/netfilter_nft/scripts/nft_display.sh
miniupnpd/netfilter_nft/scripts/nft_flush.sh
miniupnpd/netfilter_nft/scripts/nft_init.sh
miniupnpd/netfilter_nft/scripts/nft_removeall.sh
miniupnpd/options.c

Hello! I was looking through the nftables-related code to try to understand how it works and decided to make a few small improvements. Would love your feedback!
1. Spelling fix: routeing --> routing
2. Fix typo where we're incorrectly checking for `$TABLE` instead of `$NAT_TABLE` in `nft_removeall.sh`
3. Split `NAT` and `TABLE` everywhere for consistency

A few nftables fixes

---

CONTRIBUTING
README
miniupnpc/Makefile
miniupnpc/README

I have changed "Github" and "github" to "GitHub".

Fix capitalisation of GitHub

---

miniupnpc/Makefile.mingw

Similar to the other Makefile.

build: respect CFLAGS in makefile.mingw

---

miniupnpc/CMakeLists.txt
miniupnpc/Makefile
miniupnpc/miniupnpc.pc.in

miniupnpc/CMakeLists.txt: generate and install miniupnpc.pc

---

miniupnpd/miniupnpd.conf

Hello.
The address of a STUN-server mentioned in this file changed.
See: https://stunprotocol.org/
The old address doesn't work with miniupnp, the new address does work.
I also added more newlines for better readability.

miniupnpd.conf: Update the address of a STUN-server

---

miniupnpd/pf/obsdrdr.c
miniupnpd/pf/pfpinhole.c
miniupnpd/pf/rtickets.h

Pull request 674

---

appveyor.yml

https://blog.pypi.org/posts/2023-06-26-deprecate-egg-uploads/

Do not upload .egg to PyPI anymore

---

miniupnpd/Changelog.txt
miniupnpd/netfilter_nft/Makefile
miniupnpd/netfilter_nft/nftnlrdr.c
miniupnpd/netfilter_nft/nftnlrdr_misc.c
miniupnpd/netfilter_nft/nftnlrdr_misc.h
miniupnpd/netfilter_nft/nftpinhole.c
miniupnpd/netfilter_nft/testnftnlrdr.c
miniupnpd/netfilter_nft/testnftpinhole.c

fixes of NFTABLES pinout support

---

miniupnpd/upnppinhole.c

print empty string instead of null in ipv6 lease file

---

.github/workflows/miniupnpc_wheels.yml

I am not specifically recommending this, but Universal2 wheels had been requested at https://github.com/miniupnp/miniupnp/issues/616#issuecomment-1280122092 so I figured I'd make this available for consideration.

add Universal2 'arch'

---

appveyor.yml

appveyor.yml: build for python 3.12 as well and add source distribution file

---

.github/workflows/codeql-analysis.yml
.github/workflows/i586-mingw32msvc.yml
.github/workflows/i686-w64-mingw32.yml
.github/workflows/main.yml
.github/workflows/miniupnpd.yml
.github/workflows/x86_64-w64-mingw32.yml

- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
- https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

update actions in github workflows

---

miniupnpc/CMakeLists.txt
miniupnpc/Changelog.txt
miniupnpc/Makefile
miniupnpc/apiversions.txt
miniupnpc/include/miniupnpc.h
miniupnpc/src/miniupnpc.c
miniupnpc/src/upnpc.c
miniupnpc/src/upnpcommands.c

miniupnpc.c: use SOCKET under windows
